sudo: required
services: docker
script: docker build . -t cs50/ecs
before_deploy: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
deploy:
  provider: script
  script: docker push cs50/ecs
notifications:
  slack:
    secure: oVLd2isiSdo0wlDSZKDaFK3S7jqlAXS1klYR3RV4cU3IQ2lVazdYTooP+LTWSK6/uCLRVXUBbk1T+QZR+osYQXkhEiI1cTKf1+lGs8G0RfeP54logOGaZRsAvPJetPcheMgRc3HARXAAHhT17oVHBVg9agUPZbajNj0DOAR9gLR1qLYT7a00b64D7tkeUDho0lf1w2umuM6iKh3gov6HXXRyj0789OjYRPQ4+B1PQ79bwvpQ4/Jh4yXMmADvVPkHmQ6SASMCacACCcEoc2rEUb52zRtCusz58DIPTGr2gTzD0s9WeYe4U4OiYzERSgAu7A2+Qff0q+6GXB+zNeiz8Ibao6G13r5q6hMK3vNuAV3+IMHZ/Y0eqAPpKvn6WLyMPsXZBC1/EbiYmn/bkJy/KmefHkOghwsUocueBTtXYYFJoR477+R86RVusF3SOW22ih2tAVZ/kpH/UwQ0s7Fp+5wrdpgp3bpqY5o8+lTJ+KKL3/ua/RJ6Eap58F+QHmXJCrXrH6v+/upWLf3nedSgB6UTBSRpYJmn1HVOk0nly5oXUqu4QSOgRma4Mufp3+qicjpT4W0cbLlXzGf0273lH00aZGkO/dhfUwpbk7UeIeHX3G3SZDmocyeyV/g5b+dy2lgHG905Wp9n9YDR4xyRLFFHBAXcUMlE1ZGTyoGqXrA=
